# Generate features by composition

# Generate features by composition

In [6]:
import pandas as pd

# get data of mp/aflow/exp from the file 
mp_df = pd.read_csv("mp_band_gap.csv")
aflow_df = pd.read_csv("aflow_band_gap.csv")
exp_df = pd.read_csv("exp_band_gap.csv")

In [7]:
# Take a look at the degree of data difference between mp and aflow.
same_df = pd.merge(mp_df, aflow_df, on='composition', how='inner')
same_df.rename(columns={'band_gap_x': 'mp_band_gap', 'band_gap_y': 'aflow_band_gap'}, inplace=True)
same_df['diff'] = abs(same_df['mp_band_gap'] - same_df['aflow_band_gap'])
same_df.head(10)

   composition  mp_band_gap  aflow_band_gap     diff
0        Ac2O3       3.5226         3.52160  0.00100
1       Ac2Br6       4.1033         4.10840  0.00510
2       Ac2Cl6       5.0865         5.07780  0.00870
3    Ag2Au4F16       0.2585         0.58330  0.32480
4    Ag8Bi4O12       0.3872         0.65470  0.26750
5      Ag4C2O6       0.4736         0.91945  0.44585
6  Ag4Ge2Pb2S8       1.3699         1.59180  0.22190
7     Ag4Ge2S6       0.4646         0.99040  0.52580
8     Ag2Hg1I4       1.2219         1.47050  0.24860
9     Ag8Hg4O8       0.4103         0.78440  0.37410

In [8]:
same_df.describe()

       mp_band_gap  aflow_band_gap        diff
count   939.000000      939.000000  939.000000
mean      1.730437        1.791101    0.189166
std       1.209586        1.175689    0.365709
min       0.000100        0.097700    0.000100
25%       0.807200        0.892050    0.016953
50%       1.477000        1.593400    0.064533
75%       2.360000        2.419887    0.224562
max       5.853700        5.747721    4.240700

In [9]:
print("Num of diff > 1.0: ", len(same_df[same_df['diff'] > 1.0]))
print("Ratio of diff > 1.0: ", len(same_df[same_df['diff'] > 1.0]) / len(same_df))

Num of diff > 1.0:  32
Ratio of diff > 1.0:  0.03407880724174654

In [10]:
# both mp and aflow are dft calculations data, so combine them
dft_df = pd.concat([mp_df, aflow_df], ignore_index=True)
dft_df.shape

(27776, 2)

## Feature Engineering

In [11]:
# Change the name of composition column
dft_df.rename(columns={'composition': 'composition_str'}, inplace=True)
exp_df.rename(columns={'composition': 'composition_str'}, inplace=True)

In [12]:
dft_df.head()

  composition_str  band_gap
0           Ac2O3    3.5226
1         Ac16S24    2.2962
2       Ac1Ag1Te2    0.0794
3        Ac1Al1O3    4.1024
4          Ac2Br6    4.1033

In [13]:
# transform the composition_str column to composition column
from matminer.featurizers.conversions import StrToComposition

stc = StrToComposition(target_col_id='composition')
dft_df = stc.featurize_dataframe(dft_df, col_id="composition_str", pbar=True)

/home/codespace/.python/current/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
StrToComposition: 100%|██████████| 27776/27776 [00:06<00:00, 4218.75it/s]

In [14]:
exp_df = stc.featurize_dataframe(exp_df, col_id="composition_str", pbar=True)

StrToComposition: 100%|██████████| 3782/3782 [00:00<00:00, 5449.44it/s]

In [15]:
dft_df.head()

  composition_str  band_gap   composition
0           Ac2O3    3.5226       (Ac, O)
1         Ac16S24    2.2962       (Ac, S)
2       Ac1Ag1Te2    0.0794  (Ac, Ag, Te)
3        Ac1Al1O3    4.1024   (Ac, Al, O)
4          Ac2Br6    4.1033      (Ac, Br)

In [16]:
exp_df.head()

  composition_str  band_gap   composition
0   Hg0.7Cd0.3Te1      0.35  (Hg, Cd, Te)
1          Cu1Br1      3.08      (Cu, Br)
2           Lu1P1      1.30       (Lu, P)
3       Cu3Sb1Se4      0.40  (Cu, Sb, Se)
4           Zn1O1      3.44       (Zn, O)

In [17]:
# composition-based features
# very long time to run
from matminer.featurizers.composition import ElementProperty
featurizer = ElementProperty.from_preset('magpie') 	# extracting features from a predefined database， e.g. magpie, jarvis, etc.
dft_featurized_df = featurizer.featurize_dataframe(dft_df, col_id='composition')

/home/codespace/.python/current/lib/python3.12/site-packages/matminer/utils/data.py:326: UserWarning: MagpieData(impute_nan=False):
In a future release, impute_nan will be set to True by default.
                    This means that features that are missing or are NaNs for elements
                    from the data source will be replaced by the average of that value
                    over the available elements.
                    This avoids NaNs after featurization that are often replaced by
                    dataset-dependent averages.
  warnings.warn(f"{self.__class__.__name__}(impute_nan=False):\n" + IMPUTE_NAN_WARNING)
ElementProperty: 100%|██████████| 27776/27776 [00:56<00:00, 489.95it/s]

In [18]:
dft_featurized_df.head()

,composition_str,band_gap,composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,Ac2O3,3.5226,"(Ac, O)",8.0,89.0,81.0,40.4,38.88,8.0,14.0,...,0.0,0.0,0.0,0.0,12.0,225.0,213.0,97.20,102.240,12.0
1,Ac16S24,2.2962,"(Ac, S)",16.0,89.0,73.0,45.2,35.04,16.0,14.0,...,0.0,0.0,0.0,0.0,70.0,225.0,155.0,132.00,74.400,70.0
2,Ac1Ag1Te2,0.0794,"(Ac, Ag, Te)",47.0,89.0,42.0,60.0,14.50,52.0,14.0,...,0.0,0.0,0.0,0.0,152.0,225.0,73.0,188.50,36.500,152.0
3,Ac1Al1O3,4.1024,"(Ac, Al, O)",8.0,89.0,81.0,25.2,25.52,8.0,14.0,...,0.0,0.0,0.0,0.0,12.0,225.0,213.0,97.20,102.240,12.0
4,Ac2Br6,4.1033,"(Ac, Br)",35.0,89.0,54.0,48.5,20.25,35.0,14.0,...,0.0,0.0,0.0,0.0,64.0,225.0,161.0,104.25,60.375,64.0

In [19]:
exp_featurized_df = featurizer.featurize_dataframe(exp_df, col_id='composition')
exp_featurized_df.head()

ElementProperty: 100%|██████████| 3782/3782 [00:08<00:00, 449.05it/s]

,composition_str,band_gap,composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,Hg0.7Cd0.3Te1,0.35,"(Hg, Cd, Te)",48.0,80.0,32.0,61.20,13.1600,52.0,70.0,...,0.000000,0.000000,0.000000,0.0,152.0,194.0,42.0,163.200,11.200,152.0
1,Cu1Br1,3.08,"(Cu, Br)",29.0,35.0,6.0,32.00,3.0000,29.0,64.0,...,0.000000,0.000000,0.000000,0.0,64.0,225.0,161.0,144.500,80.500,64.0
2,Lu1P1,1.30,"(Lu, P)",15.0,71.0,56.0,43.00,28.0000,15.0,41.0,...,0.002247,0.001124,0.001124,0.0,2.0,194.0,192.0,98.000,96.000,2.0
3,Cu3Sb1Se4,0.40,"(Cu, Sb, Se)",29.0,51.0,22.0,34.25,4.1875,34.0,64.0,...,0.000000,0.000000,0.000000,0.0,14.0,225.0,211.0,112.125,98.125,14.0
4,Zn1O1,3.44,"(Zn, O)",8.0,30.0,22.0,19.00,11.0000,8.0,69.0,...,0.000000,0.000000,0.000000,0.0,12.0,194.0,182.0,103.000,91.000,12.0

In [20]:
# save the data to csv file
import os
if not os.path.exists("./feature_data"):
    os.makedirs("./feature_data")
dft_featurized_df.to_csv("./feature_data/dft_featurized.csv", index=False)
exp_featurized_df.to_csv("./feature_data/exp_featurized.csv", index=False)

In [21]:
# check the number of elements in the composition of dft and exp data
# dft data
dft_featurized_df.loc[:, 'composition'].apply(lambda x: len(x.elements)).describe()

count    27776.000000
mean         3.295723
std          0.630601
min          2.000000
25%          3.000000
50%          3.000000
75%          4.000000
max          4.000000
Name: composition, dtype: float64

In [22]:
# exp data
exp_featurized_df.loc[:, 'composition'].apply(lambda x: len(x.elements)).describe()

count    3782.000000
mean        2.894500
std         0.795203
min         2.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: composition, dtype: float64

- dft calculation data has elements from 2 to 4.
- experiment data has elements from 2 to 4.